server:
  port: 9000
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    本地配置
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yoake_shop
  #文件上传配置
  servlet:
    multipart:
      #单个文件和文件上传(多个文件)的最大MB
      max-file-size: 100MB
      max-request-size: 100MB

#sping事务管理日志启动
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#mubatisplus配置
mybatis-plus:
  type-aliases-package: com.shop.service.pojo  #别名扫描包
  mapper-locations: "classpath*:/mapper/**/*.xml" #这个是Mapper.xml文件地址,此为默认值
  configuration:
    map-underscore-to-camel-case: true  #开启下划线和驼峰的映射
    cache-enabled: false #是否开启二级缓存,mp提供了EhCache分布式缓存,但现在项目多以redis为主
    #EhCache 是一个纯Java的进程内缓存框架，具有快速、精干等特点，是Hibernate中默认CacheProvider。
    #Ehcache是一种广泛使用的开源Java分布式缓存。主要面向通用缓存,Java EE和轻量级容器。它具有内存和磁盘存储，
    #缓存加载器,缓存扩展,缓存异常处理程序,一个gzip缓存servlet过滤器,支持REST和SOAP api等特点。
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

  #mp新增的配置
  global-config:
    db-config:
      update-strategy: not_null #更新策略:只更新非空字段
      id-type: auto  #使用数据库自带的id自增方法,如果不开启默认是mp自带的雪花算法生成的id
#沙箱支付配置
alipay:
  appId: 9021000135613057
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCACHaTnhlof6QC8Ur9pKVsIr2lMh59iYOj7kA9irOTWwfLN0gd9rY2zEc4xnojeQqKQgr6f3Z505/dA1CgSxoFr4E5+AU8yEm1DdL/9gGuP1BJEyPYM33gE/nwLhiCMI6Xtd9f7nV+eKF+x7dZxodGQkmiteeD50T+iRCmddtjxGBMI9f3kEPgupJHgp0dfe/EZVjKk/rZaOTWXcUzZ+gWJDiU4tinFmbCtDFJs1iAPET+CYMNCBBw7Q4GFVLj0fmCQTWPzM9O8CFbE5ErdpQAw8zz0c0OCJ/ewt/f5iPohy10a3HOWuNVs/JZNhOXklDDu4k5TXZk/r01sFYKvmelAgMBAAECggEAHiTf9iV1CftzXBX/d/R51hnf2LMSJrBnxALmMRck7H60OQ5M9nENuZ0i76UbQJrQ9nhSKWQ1Or2ul9Sd+P91ov0NSd6xLPxjDjOxB/6dqq7RckMFX3PQIR/S6s+PiadxCxsQ+n8kPqCcNUNEUejCFLKqr5pwZcffoKYYu3hoLPbL8zUXqbth1negI1v+RkRfUtoF8SIWUA/Dt15/mjdFsZXV3UBe6M/bezGOaERfx9rS4mz7NPKzzbaE4xE2FFGH4wqtUUz1tE0ajiaJMK/4U60nz2IIOCo0HnOkIRKJnRY+jsxrNhofT0WD2pOUG1dcD/FL5bfnXjASEGHc5VAVCQKBgQC+GvKjStF1PPoPypZnE54E5RA9Sfc3jqF8dPOmwN69s/4iQuqOQKu6rYZ8RG8B6wrzJx0vzHMTbRjX8OK+17Ch/k3T02U4bjs3ciyWj/WQAAiXWx1pi0kZK/f0uQdzespWYp1FJex0hNId9EOEPG21NbBFxhJn3h/6Z/vf2I/0hwKBgQCsaYSk8wp4M+dsG113vB5GANty2gmkfyOXYXoyNku2usC5l2IKEtF3LEoNHzxOroAl6zuadlao7LIXEHvsyL5sLar48nyksZudXvqzNmD6YssDN5VNvXC2xLcIaBhILTvme1/o/a/xsj3KtCEi5tC7r80EOKrlR6rkpEt8SDK5cwKBgEOJqVgP9ZgUILbJf2OBWatdgcZ0Z6rKNl7T4dgFP1zf/FJJubDuEtSQX234lgN1cH9wDvNzTBLDuIbHIpcwY6U5hobR3G0O5GTPYD3hSRlumZ7EFQ/xFvglYcMElTwWjJniEQOG9Jl0sn1H0VDCcytktoojU1ipVm0M0jP1aTczAoGAKFsafTGWRcSAasGNAzW5MFGLDDsU/rfzsL9URuSGnGLiMY7Jl+oHtYlcW+3vw8r8m+OPs/v3FNsyZEurdiUWzWNzHYpEupgIALH2pHQaBwGQ21PrUqMA+wbYgNM8u8g6uRwvuu2GfWBnLkczamP0f7oKlu5csgYwbgw2zwRnOxkCgYB4lKXe6/aHlXNAzK/0irdrxqR/FayNeoLdAYKYBCx5iFgvGKVIvErY9qF3Q+mPrkd6hzebGDalU8sEdcGPdqix36VUOxeV0O60hiQqOTYYeEOvT/C5KPtqxjo+I9iB2K8n69mPFfto+QgMDRlgh3Lw1n/HItgjlXZLkBxWbtfDaw==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAozJAdcmTeJxMYhHbkcrexlkgTkTPgVSOzU5AXPqeiK3A9BSXI7kbfCBkqrAMtr3I1AbN+wz8sgp+QtBQhlgesSFKXvQWz+raoFimQDuzAecO/ix9dhNI+XdSabvxpZan0QVIRCPG/QoSMan2cHoMv8lgjGhIjoBQ7sKbrfcMVGrUX70ueffotdHlY9uLX7gxphnaOjGEXoJFcF8TrycQ6I4Irnja7FjZElj1ZfB/BFil7ppKl2hFDVosCJirCSZXjIZZmllD3rpTpSaLK2biHwy8jyyhSXak9y12ymPk1RSPXg9/OYHEKyOKAqHug4zKPYTfLeN0IJUMvDyGH77HTwIDAQAB
  notifyUrl:  http://zvkxf6.natappfree.cc/alipay/notify


